### ISSUE TITLE
Installation fails on OS X with Perl 5.16

### ISSUE THREAD

**Issue by hollie** [daxim/Module-CPANTS-Analyse#3]
Hello,

I'm trying to setup a Dist::Zilla build environment on OS X 10.8.2 running on Perl 5.16.0 installed with Perlbrew.

I'm almost there, but the Module-CPANTS-Analyse installation fails. 

Is there anyhting I can do to help you to get this working?

The error report is attached below.

Kind regards,
 Lieven.

lieven$ cat /Users/lieven/.cpanm/build.log
cpanm (App::cpanminus) 1.5018 on perl 5.016000 built for darwin-2level
Work directory is /Users/lieven/.cpanm/work/1351764108.10381
You have make /usr/bin/make
You have LWP 6.04
You have /usr/bin/tar: bsdtar 2.8.3 - libarchive 2.8.3
You have /usr/bin/unzip
Searching Module::CPANTS::Analyse on cpanmetadb ...
--> Working on Module::CPANTS::Analyse
Fetching http://www.cpan.org/authors/id/D/DA/DAXIM/Module-CPANTS-Analyse-0.86.tar.gz
-> OK
Unpacking Module-CPANTS-Analyse-0.86.tar.gz
Entering Module-CPANTS-Analyse-0.86
Checking configure dependencies from META.yml
Checking if you have Module::Build 0.4 ... Yes (0.4003)
Configuring Module-CPANTS-Analyse-0.86
Running Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Module-CPANTS-Analyse' version '0.86'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::More 0 ... Yes (0.98)
Checking if you have Test::Warn 0.11 ... Yes (0.24)
Checking if you have Test::NoWarnings 0 ... Yes (1.04)
Checking if you have Test::Deep 0 ... Yes (0.110)
Checking if you have Cwd 0 ... Yes (3.39_02)
Checking if you have Module::Signature 0 ... Yes (0.68)
Checking if you have File::chdir 0 ... Yes (0.1007)
Checking if you have CPAN::DistnameInfo 0.06 ... Yes (0.12)
Checking if you have YAML::Any 0 ... Yes (0.84)
Checking if you have Text::CSV_XS 0.45 ... Yes (0.91)
Checking if you have Test::CPAN::Meta::YAML::Version 0 ... Yes (0.21)
Checking if you have Software::License 0.003 ... Yes (0.103004)
Checking if you have Archive::Tar 1.48 ... Yes (1.82)
Checking if you have List::MoreUtils 0 ... Yes (0.33)
Checking if you have LWP::Simple 0 ... Yes (6.00)
Checking if you have ExtUtils::Manifest 0 ... Yes (1.61)
Checking if you have File::Slurp 0 ... Yes (9999.19)
Checking if you have Array::Diff 0.04 ... Yes (0.07)
Checking if you have File::Find::Rule 0 ... Yes (0.33)
Checking if you have Module::Pluggable 2.96 ... Yes (4.0)
Checking if you have Pod::Simple::Checker 2.02 ... Yes (3.20)
Checking if you have version 0.73 ... Yes (0.99)
Checking if you have Class::Accessor 0.19 ... Yes (0.34)
Checking if you have Archive::Any 0.06 ... Yes (0.0932)
Checking if you have Module::ExtractUse 0.18 ... Yes (0.28)
Checking if you have Readonly 0 ... Yes (1.03)
Checking if you have Set::Scalar 0 ... Yes (1.25)
Checking if you have IO::Capture 0.05 ... Yes (0.05)
Building and testing Module-CPANTS-Analyse-0.86
Building Module-CPANTS-Analyse
t/00_load.t ................. ok
t/02_kwalitee.t ............. ok
t/03_plugins.t .............. ok
t/05_testdir.t .............. ok
t/05_testfile.t ............. ok
# Failed test 'kwalitee of t/eg/Text-CSV_XS-0.40.tgz'
# at t/10_analyse.t line 479.
# Compared $data->{"metayml_conforms_spec_current"}
# got : '0'
# expect : '1'
# $VAR1 = {
# 'buildtool_not_executable' => 1,
# 'distributed_by_debian' => 1,
# 'easily_repackageable' => 1,
# 'easily_repackageable_by_debian' => 1,
# 'easily_repackageable_by_fedora' => 1,
# 'extractable' => 1,
# 'extracts_nicely' => 1,
# 'fits_fedora_license' => 1,
# 'has_better_auto_install' => 1,
# 'has_buildtool' => 1,
# 'has_changelog' => 1,
# 'has_example' => 1,
# 'has_humanreadable_license' => 1,
# 'has_license_in_source_file' => 1,
# 'has_manifest' => 1,
# 'has_meta_yml' => 1,
# 'has_no_bugs_reported_in_debian' => 1,
# 'has_no_patches_in_debian' => 0,
# 'has_proper_version' => 1,
# 'has_readme' => 1,
# 'has_separate_license_file' => 0,
# 'has_test_pod' => 1,
# 'has_test_pod_coverage' => 1,
# 'has_tests' => 1,
# 'has_tests_in_t_dir' => 1,
# 'has_version' => 1,
# 'has_version_in_each_file' => 1,
# 'has_working_buildtool' => 1,
# 'kwalitee' => 39,
# 'latest_version_distributed_by_debian' => 0,
# 'manifest_matches_dist' => 1,
# 'metayml_conforms_spec_current' => 0,
# 'metayml_conforms_to_known_spec' => 0,
# 'metayml_declares_perl_version' => 0,
# 'metayml_has_license' => 1,
# 'metayml_has_provides' => 0,
# 'metayml_is_parsable' => 1,
# 'no_cpants_errors' => 1,
# 'no_generated_files' => 1,
# 'no_large_files' => 1,
# 'no_pod_errors' => 1,
# 'no_stdin_for_prompting' => 1,
# 'no_symlinks' => 1,
# 'proper_libs' => 1,
# 'use_strict' => 1,
# 'use_warnings' => 1,
# 'uses_test_nowarnings' => 0,
# 'valid_signature' => 1
# };
# Failed test 'error of t/eg/Pipe-0.03.tar.gz'
# at t/10_analyse.t line 481.
# Compared array length of $data->{"metayml_conforms_spec_current"}
# got : array with 2 element(s)
# expect : array with 9 element(s)
# $VAR1 = {
# 'easily_repackageable' => 'easily_repackageable_by_fedora',
# 'easily_repackageable_by_fedora' => 'fits_fedora_license',
# 'has_no_bugs_reported_in_debian' => 'Number of bugs reported: 2. See: <a href=http://packages.debian.org/src:libpipe-perl>Basic homepage</a>',
# 'has_version_in_each_file' => [
# 'lib/Pipe/Tube/Say.pm',
# 'lib/Pipe/Tube/Map.pm',
# 'lib/Pipe/Tube/Cat.pm',
# 'lib/Pipe/Tube/Uniq.pm',
# 'lib/Pipe/Tube/Sort.pm',
# 'lib/Pipe/Tube/Glob.pm',
# 'lib/Pipe/Tube/Find.pm',
# 'lib/Pipe/Tube/Grep.pm',
# 'lib/Pipe/Tube/Split.pm',
# 'lib/Pipe/Tube/Print.pm',
# 'lib/Pipe/Tube.pm',
# 'lib/Pipe/Tube/Chomp.pm',
# 'lib/Pipe/Tube/For.pm',
# 'lib/Pipe/Tube/Tuple.pm'
# ],
# 'manifest_matches_dist' => [
# 'MANIFEST (27) does not match dist (26):',
# 'Missing in MANIFEST: ',
# 'Missing in Dist: META.yml'
# ],
# 'metayml_conforms_spec_current' => [
# '1.4',
# 'Expected a map structure from data string or file. [Validation: 1.4]'
# ],
# 'metayml_conforms_to_known_spec' => [
# '1.0',
# 'Expected a map structure from data string or file. [Validation: 1.0]'
# ],
# 'valid_signature' => -1
# };
# Failed test 'kwalitee of t/eg/PPI-HTML-1.07.tar.gz'
# at t/10_analyse.t line 479.
# Compared $data->{"metayml_conforms_to_known_spec"}
# got : '0'
# expect : '1'
# $VAR1 = {
# 'buildtool_not_executable' => 1,
# 'distributed_by_debian' => 0,
# 'easily_repackageable' => 1,
# 'easily_repackageable_by_debian' => 1,
# 'easily_repackageable_by_fedora' => 1,
# 'extractable' => 1,
# 'extracts_nicely' => 1,
# 'fits_fedora_license' => 1,
# 'has_better_auto_install' => 1,
# 'has_buildtool' => 1,
# 'has_changelog' => 1,
# 'has_example' => 1,
# 'has_humanreadable_license' => 1,
# 'has_license_in_source_file' => 1,
# 'has_manifest' => 1,
# 'has_meta_yml' => 1,
# 'has_no_bugs_reported_in_debian' => 0,
# 'has_no_patches_in_debian' => 0,
# 'has_proper_version' => 1,
# 'has_readme' => 1,
# 'has_separate_license_file' => 1,
# 'has_test_pod' => 1,
# 'has_test_pod_coverage' => 0,
# 'has_tests' => 1,
# 'has_tests_in_t_dir' => 1,
# 'has_version' => 1,
# 'has_version_in_each_file' => 1,
# 'has_working_buildtool' => 1,
# 'kwalitee' => 37,
# 'latest_version_distributed_by_debian' => 0,
# 'manifest_matches_dist' => 1,
# 'metayml_conforms_spec_current' => 0,
# 'metayml_conforms_to_known_spec' => 0,
# 'metayml_declares_perl_version' => 1,
# 'metayml_has_license' => 1,
# 'metayml_has_provides' => 0,
# 'metayml_is_parsable' => 1,
# 'no_cpants_errors' => 1,
# 'no_generated_files' => 1,
# 'no_large_files' => 1,
# 'no_pod_errors' => 1,
# 'no_stdin_for_prompting' => 1,
# 'no_symlinks' => 1,
# 'proper_libs' => 1,
# 'use_strict' => 1,
# 'use_warnings' => 0,
# 'uses_test_nowarnings' => 0,
# 'valid_signature' => 1
# };
# Failed test 'error of t/eg/PPI-HTML-1.07.tar.gz'
# at t/10_analyse.t line 481.
# Compared array length of $data->{"metayml_conforms_spec_current"}
# got : array with 2 element(s)
# expect : array with 4 element(s)
# $VAR1 = {
# 'metayml_conforms_spec_current' => [
# '1.4',
# 'Expected a map structure from data string or file. [Validation: 1.4]'
# ],
# 'metayml_conforms_to_known_spec' => [
# '1.0',
# 'Expected a map structure from data string or file. [Validation: 1.0]'
# ],
# 'valid_signature' => -1
# };
# Failed test 'kwalitee of t/eg/App-Wack-0.05.tar.gz'
# at t/10_analyse.t line 479.
# Compared $data->{"metayml_conforms_spec_current"}
# got : '0'
# expect : '1'
# $VAR1 = {
# 'buildtool_not_executable' => 1,
# 'distributed_by_debian' => 0,
# 'easily_repackageable' => 1,
# 'easily_repackageable_by_debian' => 1,
# 'easily_repackageable_by_fedora' => 1,
# 'extractable' => 1,
# 'extracts_nicely' => 1,
# 'fits_fedora_license' => 1,
# 'has_better_auto_install' => 1,
# 'has_buildtool' => 1,
# 'has_changelog' => 1,
# 'has_example' => 1,
# 'has_humanreadable_license' => 0,
# 'has_license_in_source_file' => 1,
# 'has_manifest' => 1,
# 'has_meta_yml' => 1,
# 'has_no_bugs_reported_in_debian' => 0,
# 'has_no_patches_in_debian' => 0,
# 'has_proper_version' => 1,
# 'has_readme' => 1,
# 'has_separate_license_file' => 0,
# 'has_test_pod' => 1,
# 'has_test_pod_coverage' => 1,
# 'has_tests' => 1,
# 'has_tests_in_t_dir' => 1,
# 'has_version' => 1,
# 'has_version_in_each_file' => 1,
# 'has_working_buildtool' => 1,
# 'kwalitee' => 37,
# 'latest_version_distributed_by_debian' => 0,
# 'manifest_matches_dist' => 1,
# 'metayml_conforms_spec_current' => 0,
# 'metayml_conforms_to_known_spec' => 0,
# 'metayml_declares_perl_version' => 0,
# 'metayml_has_license' => 1,
# 'metayml_has_provides' => 1,
# 'metayml_is_parsable' => 1,
# 'no_cpants_errors' => 1,
# 'no_generated_files' => 1,
# 'no_large_files' => 1,
# 'no_pod_errors' => 1,
# 'no_stdin_for_prompting' => 1,
# 'no_symlinks' => 1,
# 'proper_libs' => 1,
# 'use_strict' => 1,
# 'use_warnings' => 1,
# 'uses_test_nowarnings' => 0,
# 'valid_signature' => 1
# };
# Failed test 'kwalitee of t/eg/Term-Title-0.03.tar.gz'
# at t/10_analyse.t line 479.
# Compared $data->{"metayml_conforms_spec_current"}
# got : '0'
# expect : '1'
# $VAR1 = {
# 'buildtool_not_executable' => 1,
# 'distributed_by_debian' => 0,
# 'easily_repackageable' => 1,
# 'easily_repackageable_by_debian' => 1,
# 'easily_repackageable_by_fedora' => 1,
# 'extractable' => 1,
# 'extracts_nicely' => 1,
# 'fits_fedora_license' => 1,
# 'has_better_auto_install' => 1,
# 'has_buildtool' => 1,
# 'has_changelog' => 1,
# 'has_example' => 0,
# 'has_humanreadable_license' => 1,
# 'has_license_in_source_file' => 1,
# 'has_manifest' => 1,
# 'has_meta_yml' => 1,
# 'has_no_bugs_reported_in_debian' => 0,
# 'has_no_patches_in_debian' => 0,
# 'has_proper_version' => 1,
# 'has_readme' => 1,
# 'has_separate_license_file' => 1,
# 'has_test_pod' => 1,
# 'has_test_pod_coverage' => 1,
# 'has_tests' => 1,
# 'has_tests_in_t_dir' => 1,
# 'has_version' => 1,
# 'has_version_in_each_file' => 1,
# 'has_working_buildtool' => 1,
# 'kwalitee' => 39,
# 'latest_version_distributed_by_debian' => 0,
# 'manifest_matches_dist' => 1,
# 'metayml_conforms_spec_current' => 0,
# 'metayml_conforms_to_known_spec' => 0,
# 'metayml_declares_perl_version' => 1,
# 'metayml_has_license' => 1,
# 'metayml_has_provides' => 1,
# 'metayml_is_parsable' => 1,
# 'no_cpants_errors' => 1,
# 'no_generated_files' => 1,
# 'no_large_files' => 1,
# 'no_pod_errors' => 1,
# 'no_stdin_for_prompting' => 1,
# 'no_symlinks' => 1,
# 'proper_libs' => 1,
# 'use_strict' => 1,
# 'use_warnings' => 1,
# 'uses_test_nowarnings' => 0,
# 'valid_signature' => 1
# };
# Failed test 'kwalitee of t/eg/Parse-Fedora-Packages-0.02.tar.gz'
# at t/10_analyse.t line 479.
# Compared $data->{"metayml_conforms_spec_current"}
# got : '0'
# expect : '1'
# $VAR1 = {
# 'buildtool_not_executable' => 1,
# 'distributed_by_debian' => 0,
# 'easily_repackageable' => 1,
# 'easily_repackageable_by_debian' => 1,
# 'easily_repackageable_by_fedora' => 1,
# 'extractable' => 1,
# 'extracts_nicely' => 1,
# 'fits_fedora_license' => 1,
# 'has_better_auto_install' => 1,
# 'has_buildtool' => 1,
# 'has_changelog' => 1,
# 'has_example' => 0,
# 'has_humanreadable_license' => 0,
# 'has_license_in_source_file' => 1,
# 'has_manifest' => 1,
# 'has_meta_yml' => 1,
# 'has_no_bugs_reported_in_debian' => 0,
# 'has_no_patches_in_debian' => 0,
# 'has_proper_version' => 1,
# 'has_readme' => 1,
# 'has_separate_license_file' => 0,
# 'has_test_pod' => 1,
# 'has_test_pod_coverage' => 1,
# 'has_tests' => 1,
# 'has_tests_in_t_dir' => 1,
# 'has_version' => 1,
# 'has_version_in_each_file' => 1,
# 'has_working_buildtool' => 1,
# 'kwalitee' => 37,
# 'latest_version_distributed_by_debian' => 0,
# 'manifest_matches_dist' => 1,
# 'metayml_conforms_spec_current' => 0,
# 'metayml_conforms_to_known_spec' => 0,
# 'metayml_declares_perl_version' => 0,
# 'metayml_has_license' => 1,
# 'metayml_has_provides' => 1,
# 'metayml_is_parsable' => 1,
# 'no_cpants_errors' => 1,
# 'no_generated_files' => 1,
# 'no_large_files' => 1,
# 'no_pod_errors' => 1,
# 'no_stdin_for_prompting' => 1,
# 'no_symlinks' => 1,
# 'proper_libs' => 1,
# 'use_strict' => 1,
# 'use_warnings' => 1,
# 'uses_test_nowarnings' => 1,
# 'valid_signature' => 1
# };
# Failed test 'kwalitee of t/eg/Capture-Tiny-0.05.tar.gz'
# at t/10_analyse.t line 479.
# Compared $data->{"metayml_conforms_spec_current"}
# got : '0'
# expect : '1'
# $VAR1 = {
# 'buildtool_not_executable' => 1,
# 'distributed_by_debian' => 0,
# 'easily_repackageable' => 1,
# 'easily_repackageable_by_debian' => 1,
# 'easily_repackageable_by_fedora' => 1,
# 'extractable' => 1,
# 'extracts_nicely' => 1,
# 'fits_fedora_license' => 1,
# 'has_better_auto_install' => 1,
# 'has_buildtool' => 1,
# 'has_changelog' => 1,
# 'has_example' => 1,
# 'has_humanreadable_license' => 1,
# 'has_license_in_source_file' => 1,
# 'has_manifest' => 1,
# 'has_meta_yml' => 1,
# 'has_no_bugs_reported_in_debian' => 0,
# 'has_no_patches_in_debian' => 0,
# 'has_proper_version' => 1,
# 'has_readme' => 1,
# 'has_separate_license_file' => 1,
# 'has_test_pod' => 1,
# 'has_test_pod_coverage' => 1,
# 'has_tests' => 1,
# 'has_tests_in_t_dir' => 1,
# 'has_version' => 1,
# 'has_version_in_each_file' => 1,
# 'has_working_buildtool' => 1,
# 'kwalitee' => 40,
# 'latest_version_distributed_by_debian' => 0,
# 'manifest_matches_dist' => 1,
# 'metayml_conforms_spec_current' => 0,
# 'metayml_conforms_to_known_spec' => 0,
# 'metayml_declares_perl_version' => 1,
# 'metayml_has_license' => 1,
# 'metayml_has_provides' => 1,
# 'metayml_is_parsable' => 1,
# 'no_cpants_errors' => 1,
# 'no_generated_files' => 1,
# 'no_large_files' => 1,
# 'no_pod_errors' => 1,
# 'no_stdin_for_prompting' => 1,
# 'no_symlinks' => 1,
# 'proper_libs' => 1,
# 'use_strict' => 1,
# 'use_warnings' => 1,
# 'uses_test_nowarnings' => 0,
# 'valid_signature' => 1
# };
# Looks like you failed 8 tests of 25.

t/10_analyse.t .............. 
Dubious, test returned 8 (wstat 2048, 0x800)
Failed 8/25 subtests 
t/analyse_afs.t ............. ok
t/analyse_axkit_xsp_l10n.t .. ok
t/analyse_devel_timer.t ..... ok
t/analyse_eg_c.t ............ ok
t/analyse_html_tiny.t ....... ok
t/analyse_test_yaml_meta.t .. ok
t/calc.t .................... ok
# Failed test 'metrics are as expected'
# at t/calc_test_yaml_meta.t line 85.
# Compared $data->{"metayml_conforms_spec_current"}
# got : '0'
# expect : '1'
# Looks like you failed 1 test of 4.

t/calc_test_yaml_meta.t ..... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
t/generated_files.t ......... ok
t/moose_as_strict.t ......... ok
t/perl5i_as_strict.t ........ ok
t/perl5i_as_warnings.t ...... ok
t/plugin_manifest.t ......... ok
t/unpack.t .................. ok
t/unpack_notextractable.t ... ok
## Test Summary Report

t/10_analyse.t            (Wstat: 2048 Tests: 25 Failed: 8)
  Failed tests:  2, 6, 8-9, 11, 14, 17, 20
  Non-zero exit status: 8
t/calc_test_yaml_meta.t   (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=21, Tests=274, 14 wallclock secs ( 0.10 usr  0.05 sys + 11.47 cusr  1.28 csys = 12.90 CPU)
Result: FAIL
Failed 2/21 test programs. 9/274 subtests failed.
-> FAIL Installing Module::CPANTS::Analyse failed.

**Comment by chorny** [comment]
Patch for this bug is available here: https://github.com/daxim/Module-CPANTS-Analyse/pull/4

**Comment by hollie** [comment]
Hi Chorny, thanks for the reference to the patch. Problem solved.
